// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.............cccccccccc.........
...........cccccccccccccccccc...
...........cccccccccccccccccc...
...........ddccccccccccccc......
...........ddccccccccccccc......
.........dd44ddddcccccc.........
.........dd44ddddcccccc.........
...........ddddddcccccc.........
...........ddddddcccccc.........
...........ffffffcccccc.........
...........ffffffcccccc.........
...........ffffffcccccc.........
.........ffffccccccccccccc......
.........ffffccccccccccccc......
ddddcccccccccccccbbccccccccc....
ddddcccccccccccccbbccccccccc....
..ddcccccccccbbbbccccbbccccc....
..ddcccccccccbbbbccccbbccccc....
....cccccccbbccccccccccbbbcc....
....cccccccbbccccccccccbbbcc....
...........ccccccccccccbbbcc....
...........ccccccccccccbbbcc....
...........ccccccccccccbbbcc....
...........ccccccccbbccbbbcc....
...........ccccccccbbccbbbcc....
...........ccccccccbbccbbbcc....
...........ccccccccbbccbbbcc....
...........ccccccbbcccccccbbc...
...........ccccccbbcccccccbbc...
...........ccccccbbcccccccccb...
...........ccccccbbcccccccccb...
.............ffffff..fffff......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
